//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kilargo.KilargoServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KilargoServices.KilargoSoap")]
    public interface KilargoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/_getAuthentication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool _getAuthentication(string _userName, string _password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/_getCategoryList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string _getCategoryList(string _userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KilargoSoapChannel : kilargo.KilargoServices.KilargoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KilargoSoapClient : System.ServiceModel.ClientBase<kilargo.KilargoServices.KilargoSoap>, kilargo.KilargoServices.KilargoSoap {
        
        public KilargoSoapClient() {
        }
        
        public KilargoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KilargoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KilargoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KilargoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool _getAuthentication(string _userName, string _password) {
            return base.Channel._getAuthentication(_userName, _password);
        }
        
        public string _getCategoryList(string _userName) {
            return base.Channel._getCategoryList(_userName);
        }
    }
}
